# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protocol import prime_pb2 as protocol_dot_prime__pb2


class PrimeCheckerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IsPrime = channel.unary_unary(
        '/protocol.PrimeChecker/IsPrime',
        request_serializer=protocol_dot_prime__pb2.IsPrimeRequest.SerializeToString,
        response_deserializer=protocol_dot_prime__pb2.IsPrimeResponse.FromString,
        )


class PrimeCheckerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def IsPrime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PrimeCheckerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IsPrime': grpc.unary_unary_rpc_method_handler(
          servicer.IsPrime,
          request_deserializer=protocol_dot_prime__pb2.IsPrimeRequest.FromString,
          response_serializer=protocol_dot_prime__pb2.IsPrimeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protocol.PrimeChecker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
