# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prime.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='prime.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bprime.proto\" \n\x0eIsPrimeRequest\x12\x0e\n\x06number\x18\x01 \x01(\x04\"3\n\x0fIsPrimeResponse\x12\x0f\n\x07isPrime\x18\x01 \x01(\x08\x12\x0f\n\x07\x64ivisor\x18\x02 \x01(\x04\x32>\n\x0cPrimeChecker\x12.\n\x07IsPrime\x12\x0f.IsPrimeRequest\x1a\x10.IsPrimeResponse\"\x00\x62\x06proto3')
)




_ISPRIMEREQUEST = _descriptor.Descriptor(
  name='IsPrimeRequest',
  full_name='IsPrimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='IsPrimeRequest.number', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=47,
)


_ISPRIMERESPONSE = _descriptor.Descriptor(
  name='IsPrimeResponse',
  full_name='IsPrimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isPrime', full_name='IsPrimeResponse.isPrime', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='divisor', full_name='IsPrimeResponse.divisor', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['IsPrimeRequest'] = _ISPRIMEREQUEST
DESCRIPTOR.message_types_by_name['IsPrimeResponse'] = _ISPRIMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IsPrimeRequest = _reflection.GeneratedProtocolMessageType('IsPrimeRequest', (_message.Message,), dict(
  DESCRIPTOR = _ISPRIMEREQUEST,
  __module__ = 'prime_pb2'
  # @@protoc_insertion_point(class_scope:IsPrimeRequest)
  ))
_sym_db.RegisterMessage(IsPrimeRequest)

IsPrimeResponse = _reflection.GeneratedProtocolMessageType('IsPrimeResponse', (_message.Message,), dict(
  DESCRIPTOR = _ISPRIMERESPONSE,
  __module__ = 'prime_pb2'
  # @@protoc_insertion_point(class_scope:IsPrimeResponse)
  ))
_sym_db.RegisterMessage(IsPrimeResponse)



_PRIMECHECKER = _descriptor.ServiceDescriptor(
  name='PrimeChecker',
  full_name='PrimeChecker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=102,
  serialized_end=164,
  methods=[
  _descriptor.MethodDescriptor(
    name='IsPrime',
    full_name='PrimeChecker.IsPrime',
    index=0,
    containing_service=None,
    input_type=_ISPRIMEREQUEST,
    output_type=_ISPRIMERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRIMECHECKER)

DESCRIPTOR.services_by_name['PrimeChecker'] = _PRIMECHECKER

# @@protoc_insertion_point(module_scope)
